# DataFrames

In [40]:
import numpy as np
import pandas as pd

In [41]:
from numpy.random import randn

In [42]:
np.random.seed(101)

In [43]:
df = pd.DataFrame(randn(4,3), ['A', 'B', 'C', 'D'], ['X', 'Y', 'Z'])

In [44]:
df

          X         Y         Z
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
C -0.848077  0.605965 -2.018168
D  0.740122  0.528813 -0.589001

In [45]:
df['X']

A    2.706850
B    0.503826
C   -0.848077
D    0.740122
Name: X, dtype: float64

In [46]:
df.X

A    2.706850
B    0.503826
C   -0.848077
D    0.740122
Name: X, dtype: float64

In [47]:
type(df)

pandas.core.frame.DataFrame

In [48]:
type(df['X'])

pandas.core.series.Series

In [49]:
df[['X', 'Y']]

          X         Y
A  2.706850  0.628133
B  0.503826  0.651118
C -0.848077  0.605965
D  0.740122  0.528813

In [50]:
df['new'] = df['X'] + df['Y']

In [51]:
df

          X         Y         Z       new
A  2.706850  0.628133  0.907969  3.334983
B  0.503826  0.651118 -0.319318  1.154944
C -0.848077  0.605965 -2.018168 -0.242112
D  0.740122  0.528813 -0.589001  1.268936

In [52]:
df.drop('new', axis=1)

          X         Y         Z
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
C -0.848077  0.605965 -2.018168
D  0.740122  0.528813 -0.589001

In [53]:
df

          X         Y         Z       new
A  2.706850  0.628133  0.907969  3.334983
B  0.503826  0.651118 -0.319318  1.154944
C -0.848077  0.605965 -2.018168 -0.242112
D  0.740122  0.528813 -0.589001  1.268936

In [54]:
df.drop('new', axis=1, inplace=True)

In [55]:
df

          X         Y         Z
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
C -0.848077  0.605965 -2.018168
D  0.740122  0.528813 -0.589001

In [56]:
df.drop('D', axis=0)

          X         Y         Z
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
C -0.848077  0.605965 -2.018168

In [57]:
df

          X         Y         Z
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
C -0.848077  0.605965 -2.018168
D  0.740122  0.528813 -0.589001

In [58]:
df.drop('D', inplace=True)

In [59]:
df

          X         Y         Z
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
C -0.848077  0.605965 -2.018168

In [60]:
df.shape

(3, 3)

In [61]:
df = pd.DataFrame(randn(4,3), ['A', 'B', 'C', 'D'], ['X', 'Y', 'Z'])

In [62]:
df

          X         Y         Z
A  0.188695 -0.758872 -0.933237
B  0.955057  0.190794  1.978757
C  2.605967  0.683509  0.302665
D  1.693723 -1.706086 -1.159119

In [63]:
df.loc['A']

X    0.188695
Y   -0.758872
Z   -0.933237
Name: A, dtype: float64

In [64]:
df.iloc[2]

X    2.605967
Y    0.683509
Z    0.302665
Name: C, dtype: float64

In [65]:
df.loc['B','Y']

np.float64(0.19079432237171562)

In [66]:
df.loc[['A','C'], ['Y','Z']]

          Y         Z
A -0.758872 -0.933237
C  0.683509  0.302665

### Part 2

In [67]:
df['X']

A    0.188695
B    0.955057
C    2.605967
D    1.693723
Name: X, dtype: float64

In [68]:
df['X'] > 0

A    True
B    True
C    True
D    True
Name: X, dtype: bool

In [70]:
df[df['X']>0]

          X         Y         Z
A  0.188695 -0.758872 -0.933237
B  0.955057  0.190794  1.978757
C  2.605967  0.683509  0.302665
D  1.693723 -1.706086 -1.159119

In [71]:
df[df['Z']<0]

          X         Y         Z
A  0.188695 -0.758872 -0.933237
D  1.693723 -1.706086 -1.159119

In [73]:
df[(df['X']>0) & (df['Z']<0)]

          X         Y         Z
A  0.188695 -0.758872 -0.933237
D  1.693723 -1.706086 -1.159119

In [74]:
df[(df['X']>0) | (df['Z']<0)]

          X         Y         Z
A  0.188695 -0.758872 -0.933237
B  0.955057  0.190794  1.978757
C  2.605967  0.683509  0.302665
D  1.693723 -1.706086 -1.159119

In [75]:
df

          X         Y         Z
A  0.188695 -0.758872 -0.933237
B  0.955057  0.190794  1.978757
C  2.605967  0.683509  0.302665
D  1.693723 -1.706086 -1.159119

In [76]:
df.reset_index()

  index         X         Y         Z
0     A  0.188695 -0.758872 -0.933237
1     B  0.955057  0.190794  1.978757
2     C  2.605967  0.683509  0.302665
3     D  1.693723 -1.706086 -1.159119

In [80]:
newind = 'CA NY WY OR '.split()

In [81]:
newind

['CA', 'NY', 'WY', 'OR']

In [82]:
df['states'] = newind

In [83]:
df

          X         Y         Z states
A  0.188695 -0.758872 -0.933237     CA
B  0.955057  0.190794  1.978757     NY
C  2.605967  0.683509  0.302665     WY
D  1.693723 -1.706086 -1.159119     OR

In [84]:
df.set_index('states')

               X         Y         Z
states
CA      0.188695 -0.758872 -0.933237
NY      0.955057  0.190794  1.978757
WY      2.605967  0.683509  0.302665
OR      1.693723 -1.706086 -1.159119

In [85]:
df

          X         Y         Z states
A  0.188695 -0.758872 -0.933237     CA
B  0.955057  0.190794  1.978757     NY
C  2.605967  0.683509  0.302665     WY
D  1.693723 -1.706086 -1.159119     OR