# Pandas Missing Data

In [1]:
import numpy as np
import pandas as pd

In [19]:
d = {'A':[1,2,np.nan], 'B':[4, np.nan, np.nan], 'C':[6,7,8]}

In [20]:
d

{'A': [1, 2, nan], 'B': [4, nan, nan], 'C': [6, 7, 8]}

In [21]:
df = pd.DataFrame(d)

In [6]:
df

     A    B  C
0  1.0  4.0  6
1  2.0  NaN  7
2  NaN  NaN  8

In [7]:
df.dropna()

     A    B  C
0  1.0  4.0  6

In [9]:
df.dropna(axis=1)

   C
0  6
1  7
2  8

In [10]:
df.dropna(thresh=2)

     A    B  C
0  1.0  4.0  6
1  2.0  NaN  7

In [22]:
df.fillna(value='Fill value')

            A           B  C
0         1.0         4.0  6
1         2.0  Fill value  7
2  Fill value  Fill value  8

In [23]:
df

     A    B  C
0  1.0  4.0  6
1  2.0  NaN  7
2  NaN  NaN  8

In [15]:
df['A'].fillna(value=df['A'].mean(), inplace=True)

C:\Users\AbbasKothari\AppData\Local\Temp\ipykernel_5248\4106936588.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['A'].fillna(value=df['A'].mean(), inplace=True)

In [24]:
df.fillna({'A': df['A'].mean()})

     A    B  C
0  1.0  4.0  6
1  2.0  NaN  7
2  1.5  NaN  8

In [25]:
df

     A    B  C
0  1.0  4.0  6
1  2.0  NaN  7
2  NaN  NaN  8